/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardLayoutImport } from './routes/dashboard/_layout'
import { Route as DashboardLayoutIndexImport } from './routes/dashboard/_layout.index'
import { Route as DashboardLayoutUrlsImport } from './routes/dashboard/_layout.urls'
import { Route as DashboardLayoutProfileImport } from './routes/dashboard/_layout.profile'
import { Route as DashboardLayoutUrlsShortUrlImport } from './routes/dashboard/_layout.urls.$shortUrl'
import { Route as DashboardLayoutAnalyticsShortUrlImport } from './routes/dashboard/_layout.analytics.$shortUrl'

// Create Virtual Routes

const DashboardImport = createFileRoute('/dashboard')()

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardLayoutRoute = DashboardLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardLayoutIndexRoute = DashboardLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardLayoutUrlsRoute = DashboardLayoutUrlsImport.update({
  path: '/urls',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardLayoutProfileRoute = DashboardLayoutProfileImport.update({
  path: '/profile',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardLayoutUrlsShortUrlRoute =
  DashboardLayoutUrlsShortUrlImport.update({
    path: '/$shortUrl',
    getParentRoute: () => DashboardLayoutUrlsRoute,
  } as any)

const DashboardLayoutAnalyticsShortUrlRoute =
  DashboardLayoutAnalyticsShortUrlImport.update({
    path: '/analytics/$shortUrl',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/_layout': {
      preLoaderRoute: typeof DashboardLayoutImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/_layout/profile': {
      preLoaderRoute: typeof DashboardLayoutProfileImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/urls': {
      preLoaderRoute: typeof DashboardLayoutUrlsImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/': {
      preLoaderRoute: typeof DashboardLayoutIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/analytics/$shortUrl': {
      preLoaderRoute: typeof DashboardLayoutAnalyticsShortUrlImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/urls/$shortUrl': {
      preLoaderRoute: typeof DashboardLayoutUrlsShortUrlImport
      parentRoute: typeof DashboardLayoutUrlsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LoginRoute,
  RegisterRoute,
  DashboardRoute.addChildren([
    DashboardLayoutRoute.addChildren([
      DashboardLayoutProfileRoute,
      DashboardLayoutUrlsRoute.addChildren([DashboardLayoutUrlsShortUrlRoute]),
      DashboardLayoutIndexRoute,
      DashboardLayoutAnalyticsShortUrlRoute,
    ]),
  ]),
])

/* prettier-ignore-end */
